# docker-compose.yml
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - FACE_DETECTION_MODEL=hog
      - MATCH_THRESHOLD=0.55
      - MULTI_IMAGE_STRATEGY=max
      - MIN_SECONDS_BETWEEN_ATTENDANCE=60
      - TIMEZONE=Asia/Jakarta
      - ADMIN_API_KEY=change-me-in-env
      - LOG_LEVEL=INFO
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts
      - ./images:/app/images
      - ./data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
